# ================================
# Activity Service Configuration (Using Config Server)
# ================================

server:
  port: 8085  # Unique port for this microservice to avoid conflict with other services

spring:
  application:
    name: activity-service  # Unique service name

  # Import configuration from Config Server
  config:
    import: optional:configserver:http://localhost:8090  # ConfigServer URL (update to match your running port)
    profiles:
      active: default

kafka:
  topic:
    name: activity-events




# ================================
# Notes / Troubleshooting
# ================================
# 1. Ensure the Config Server is running on http://localhost:8090 before starting this service.
# 2. If you need to run locally without Config Server, uncomment the sections below:
#
# spring:
#   data:
#     mongodb:
#       uri: mongodb://localhost:27017/fitnessDB
#       database: fitnessDB
#
#   kafka:
#     consumer:
#       properties:
#         spring:
#           json:
#             trusted:
#               packages=*
#     bootstrap-servers: localhost:9092
#     producer:
#       key-serializer: org.apache.kafka.common.serialization.StringSerializer
#       value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#
# kafka:
#   topic:
#     name: activity-events
#
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/
#     register-with-eureka: true
#     fetch-registry: true
#   instance:
#     lease-renewal-interval-in-seconds: 10
#     lease-expiration-duration-in-seconds: 30
#
# 3. Adjust 'server.port' if you run multiple microservices locally to avoid port conflicts.
