spring:
  application:
    name: gateway-service




  config:
    import: optional:configserver:http://localhost:8090
    profiles:
      active: default
#
#
#  cloud:
#    config:
#      enabled: false

