# ================================
# aiService properties served by Config Server
# ================================
server:
  port: 8086  # Port on which aiService will run

spring:
  application:
    name: ai-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/airecommendationfitness
      database: airecommendationfitness

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: activity-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      enable-auto-commit: true
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.fitness.aiService.model.Activity
        spring.json.trusted-packages: "*"

kafka:
  topic:
    name: activity-events

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
    key: AIzaSyAW0ry9WyJM0pLajxYA7a64hxGsex7jQww

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
