#server:
#  port: 8090
#
#spring:
#  application:
#    name: config-server
#
#  cloud:
#    config:
#      server:
#        git:
#          uri: file:///Users/amitkumar/Documents/config-repo   # aapka external repo path
#          default-label: main
#      fail-fast: true
#
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
